# Generated by Django 4.2.20 on 2025-04-05 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('special_status', 'Can read all books')]},
        ),
    ]
